name: CI

on:
  push:
    branches: ["v2"]
  pull_request:
    branches: ["v2"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  rust:
    uses: ./.github/workflows/rust.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
