name: ci

on:
  push:
    branches: ["v2"]
  schedule:
    - cron: "0 0 1 * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check --verbose
      - run: cargo clippy --workspace --all-features -- -D warnings
      - run: cargo install taplo-cli --locked
      - run: taplo fmt --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo check --workspace --all-targets --all-features --verbose
      - run: cargo check --release --workspace --all-targets --all-features --verbose

  test:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --workspace --all-features --no-fail-fast --verbose
      - run: cargo test --release --workspace --all-features --no-fail-fast --verbose

